### ISSUE TITLE
"Use Legacy Swift Language Version" is required

### ISSUE THREAD

**Issue by olivierkorner** [stormpath/stormpath-sdk-swift#29]
Since I upgraded XCode to version 8, I can't build my (Objective-C) project any more. 
I have one issue in the Stormpath pod: 
`“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.`
And the file Stormpath-Swift.h is not found in files where it was imported.
I'm using branch `swift3`.

**Comment by edjiang** [comment]
Hey @olivierkorner, I'm finalizing the update for Xcode 8 today. I think I tested the example project with either the swift2.3 or swift3 branch and it seemed to fully work; I need to look into Cocoapods's settings for the legacy Swift version though, since I don't think it's generating that flag for Xcode projects. 

I believe for now, if you enable it manually in the pod project, you should be able to compile with the current swift3 branch. 

Screenshot on where to look:

<img width="1552" alt="screen shot 2016-09-12 at 9 14 10 am" src="https://cloud.githubusercontent.com/assets/918770/18443399/92106744-78c9-11e6-92ac-de0cc0c10fa1.png">

**Comment by olivierkorner** [comment]
@edjiang Thank you!
Actually, I was able to compile my project successfully after upgrading cocoapod to the latest pre-release (1.1.0 RC1) and using swift2.3 branch.

**Comment by edjiang** [comment]
There's an official `2.0` tag that's now fully Swift 3 =] Check it out!
