### ISSUE TITLE
Removing credentials after uninstalling app

### ISSUE THREAD

**Issue by kioltk** [stormpath/stormpath-sdk-swift#37]
Hello guys, just tried to uninstall an app and to run it again - Stormpath automatically log in my previous account. Is it good behavior?

**Comment by edjiang** [comment]
Hey kioltk!

Yes, this is expected behavior. The access and refresh tokens are stored in the iOS keychain, and they can be accessed on re-install for apps with the same provisioning profile.

See this: http://stackoverflow.com/questions/20904185/how-to-delete-keychain-data-when-app-is-uninstalled

If you don't want this behavior, you could also use this (check for a NSUserDefaults key on startup, and pre-emptively `Stormpath.sharedSession.logout()` the user.

Thanks for using the iOS SDK, and feel free to reach out in the future if you have any other questions!
